# P-ROC Game Description file for Attack from Mars
PRGame:
    machineType: wpc95
    numBalls: 4

PRFlippers:
    - flipperLwR
    - flipperLwL

PRBumpers:
    - leftSlingshot
    - rightSlingshot
    - leftJet
    - rightJet
    - bottomJet

PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    # Flipper Grounded Switches
    flipperLwRightEOS:
        number: SF1
    flipperLwR:
        number: SF2
        type: NC
    flipperLwLeftEOS:
        number: SF3
    flipperLwL:
        number: SF4
        type: NC
    flipperUpRightEOS: # not used
        number: SF5
    flipperUpR:
        number: SF6
        type: NC
    flipperUpLeftEOS:  # not used
        number: SF7
    flipperUpL:
        number: SF8
        type: NC

    # Dedicated Grounded Switches
    coinSlot1:
        number: SD1
    coinSlot2:
        number: SD2
    coinSlot3:
        number: SD3
    coinSlot4:
        number: SD4
    exit:
        number: SD5
    down:
        number: SD6
    up:
        number: SD7
    enter:
        number: SD8

    # Regular Switches
    launchButton:
        number: S11
    unused_S12:
        number: S12
    startButton:
        number: S13
    plumbBobTilt:
        number: S14
    unused_S15:
        number: S15
    leftOutlane:
        number: S16
    rightReturn:
        number: S17
    shooterLane:
        number: S18

    slamTilt:
        number: S21
    coinDoorClosed:
        number: S22
    unused_S23:
        number: S23
    alwaysClosed:
        number: S24
    unused_S25:
        number: S25
    leftReturn:
        number: S26
    rightOutlane:
        number: S27
    unused_S28:
        number: S28

    troughEject:
        number: S31
        type: NC
    trough1:
        number: S32
        type: NC
    trough2:
        number: S33
        type: NC
    trough3:
        number: S34
        type: NC
    trough4:
        number: S35
        type: NC
    leftPopper:
        number: S36
        type: NC
    rightPopper:
        number: S37
        type: NC
    leftTopLane:
        number: S38

    martian6:
        number: S41
    martian7:
        number: S42
    martian4:
        number: S43
    martian5:
        number: S44
    leftMotorBank:
        number: S45
    centerMotorBank:
        number: S46
    rightMotorBank:
        number: S47
    rightTopLane:
        number: S48

    leftSlingshot:
        number: S51
    rightSlingshot:
        number: S52
    leftJet:
        number: S53
    bottomJet:
        number: S54
    rightJet:
        number: S55
    martian1:
        number: S56
    martian2:
        number: S57
    martian3:
        number: S58

    leftRampEnter:
        number: S61
    centerRampEnter:
        number: S62
    rightRampEnter:
        number: S63
    leftRampExit:
        number: S64
    rightRampExit:
        number: S65
    motorBankDown:
        number: S66
    motorBankUp:
        number: S67
    unused_S68:
        number: S68

    rightLoopHigh:
        number: S71
    rightLoopLow:
        number: S72
    leftLoopHigh:
        number: S73
    leftLoopLow:
        number: S74
    leftSaucerTarget:
        number: S75
    rightSaucerTarget:
        number: S76
    dropTarget:
        number: S77
    centerTrough:
        number: S78

    unused_S81:
        number: S81
    unused_S82:
        number: S82
    unused_S83:
        number: S83
    unused_S84:
        number: S84
    unused_S85:
        number: S85
    unused_S86:
        number: S86
    unused_S87:
        number: S87
    unused_S88:
        number: S88

PRCoils:
    flipperLwRMain:
        number: FLRM
        pulseTime: 34
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
        pulseTime: 34
    flipperLwLHold:
        number: FLLH

    autoPlunger:
        number: C01
    troughEject:
        number: C02
    leftPopper:
        number: C03
    rightPopper:
        number: C04
    leftAlienLow:
        number: C05
        pulseTime: 13
    leftAlienHigh:
        number: C06
        pulseTime: 13
    knocker:
        number: C07
    rightAlienHigh:
        number: C08
        pulseTime: 13
    leftSlingshot:
        number: C09
    rightSlingshot:
        number: C10
    leftJet:
        number: C11
    bottomJet:
        number: C12
    rightJet:
        number: C13
    rightAlienLow:
        number: C14
        pulseTime: 13
    saucerShake:
        number: C15
    dropTarget:
        number: C16
    motorBank:
        number: C24
    rightGate:
        number: C33
    leftGate:
        number: C34
    diverterPower:
        number: C35
    diverterHold:
        number: C36

    # Flashers
    rightRampHighFlasher:
        number: C17
    rightRampLowFlasher:
        number: C18
    rightSideHighFlasher:
        number: C19
    rightSideLowFlasher:
        number: C20
    centerArrowFlasher:
        number: C21
    jetsFlasher:
        number: C22
    saucerDomeFlasher:
        number: C23
    leftRampLeftFlashers:
        number: C25
    leftRampRightFlashers:
        number: C26
    leftSideHighFlashers:
        number: C27
    leftSideLowFlasher:
        number: C28
    strobeLight:
        number: C39

    # Special Drivers
    ledClock:
        number: C37
        pulseTime: 2
    ledData:
        number: C38

PRLamps:
    superJets:
        number: L11
    superJackpot:
        number: L12
    martianAttackMultiball:
        number: L13
    annihilation:
        number: L14
    returnToBattle:
        number: L15
    conquerMars:
        number: L16
    fiveWayCombo:
        number: L17
    dropTarget:
        number: L18

    bigObeam1:
        number: L21
    bigObeam2:
        number: L22
    bigObeam3:
        number: L23
    leftRampJackpot:
        number: L24
    leftRampArrow:
        number: L25
    lock2:
        number: L26
    lock3:
        number: L27
    centerRampJackpot:
        number: L28

    tractorBeam1:
        number: L31
    tractorBeam2:
        number: L32
    tractorBeam3:
        number: L33
    rightRampJackpot:
        number: L34
    rightRampArrow:
        number: L35
    martianAttack:
        number: L36
    ruleTheUniverse:
        number: L37
    strokeOfLuck:
        number: L38

    rightLoopArrow:
        number: L41
    centerRampArrow:
        number: L42
    leftTopLane:
        number: L43
    rightTopLane:
        number: L44
    leftMotorBank:
        number: L45
    centerMotorBank:
        number: L46
    rightMotorBank:
        number: L47
    martian4:
        number: L48

    attackMars:
        number: L51
    dcUSA:
        number: L52
    londonEngland:
        number: L53
    lightLock:
        number: L54
    lock1:
        number: L55
    pisaItaly:
        number: L56
    berlinGermany:
        number: L57
    parisFrance:
        number: L58

    martian7:
        number: L61
    martian6:
        number: L62
    atomicBlaster1:
        number: L63
    atomicBlaster2:
        number: L64
    atomicBlaster3:
        number: L65
    rightLoopJackpot:
        number: L66
    extraBall:
        number: L67
    martian5:
        number: L68

    capture1:
        number: L71
    capture2:
        number: L72
    capture3:
        number: L73
    leftLoopJackpot:
        number: L74
    leftLoopArrow:
        number: L75
    martian1:
        number: L76
    martian2:
        number: L77
    martian3:
        number: L78

    shootAgain:
        number: L81
    leftOutlane:
        number: L82
    leftReturn:
        number: L83
    rightReturn:
        number: L84
    rightOutlane:
        number: L85
    launchButton:
        number: L86
    unused_L87:
        number: L87
    startButton:
        number: L88

    # General Illumination
    gi01:  # bottom playfield
        number: G01
    gi02:  # middle playfield
        number: G02
    gi03:  # top playfield
        number: G03
    gi04:  # top insert
        number: G04
    gi05:  # bottom insert
        number: G05

PRBallSave:
    pulseCoils: [leftSlingshot, rightSlingshot, leftJet, rightJet, bottomJet, eject, topPopper, bottomPopper]
    resetSwitches:
        leftSlingshot: open
        rightSlingshot: open
        leftJet: open
        rightJet: open
        bottomJet: open
        leftOutlane: open
        leftInlane: open
        rightInlane: open
        rightOutlane: open
    stopSwitches:
        shooterLane: closed
        flipperLwL: closed
        flipperLwR: closed

PRPinmame:
    # This section is specific to running the P-ROC via Pinmame.

    # keyboard:
    #   on or off - determines whether keyboard will be enabled or not
    #   useful in a Sys11 in early debugging
    #   Note that this caused problems reading the ball trough on Demolition Man (WPC)

    # s11CreditDisplay and s11BallDisplay :
    #   If using a Sys11 game prior which has a separate Ball/Credit display, you can put them on the
    #   DMD.  If the value for a display is set to zero (or removed from YAML) it won't display.
    #   Otherwise it's the vertical position of the display from the top.  Try 1 and 15 for a start.

    # autoPatterDetection:
    #   on or off - by default, Pinmame will try to automatically detect patter requirements.
    #   there is a thread on the forum about this.  For Sys11 this should certainly be disabled,
    #   as it does nasty things.  Likely enable for other platforms but could be useful to disable.

    # doubleAlpha:
    #   0 or 1 - set to 1 if your machine has 2 lines of 16 character alphanumeric displays.
    #   This will adapt the code to properly handle the various display types in Sys11 machines (and a couple of WPC)

    # fullTroughDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when switches "trough1" through "troughX"
    #            are all active.

    # lightsOutDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when all lamps and GI are off (tilt detection).

    keyboard: off
    autoPatterDetection: off
    s11CreditDisplay: 0
    s11BallDisplay: 0
    doubleAlpha: 0
    fullTroughDisablesFlippers: 0
    lightsOutDisablesFlippers: 0
