# P-ROC Game Description file for Demolition Man

PRGame:
    machineType: wpc
    numBalls: 5

PRFlippers:
    - flipperLwR
    - flipperLwL
    - flipperUpL

PRBumpers:
    - leftSlingshot
    - rightSlingshot
    - leftJet
    - rightJet
    - topSlingshot

PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    # Demolition Man has an atypical configuration.  On most games, the upper
    # left and right switches are connected to the flipper buttons for staged
    # upper flippers.  On DM, those switches are in the big handles mounted
    # to the cabinet.  Either upper or lower right switch trigger the lower
    # right flipper, and the upper and lower left switches trigger both the
    # upper and lower left flippers.

    # Note that leftHandle and rightHandle will not drive the flippers unless
    # you write custom switch rules.  PinMAME does work on DM as of Feb 2015.
    # See https://github.com/tomlogic/pinmame for source.

    #Flipper Grounded Switches
    flipperLwRightEOS:
        number: SF1
    flipperLwR:
        number: SF2
        type: NC
    # Actually flipperLwLeftEOS, but PRFlippers uses it to trigger the upper
    # flipper if not otherwise programmed by custom switch rules.
    flipperUpL:
        number: SF3
    flipperLwL:
        number: SF4
        type: NC
    # SF5 would be flipperUpRightEOS but there isn't an upper right flipper
    flipperSwNotUsed:
        number: SF5
    rightHandle:
        number: SF6
        type: NC
    flipperUpLeftEOS:
        number: SF7
    leftHandle:
        number: SF8
        type: NC

    #Dedicated Grounded Switches
    coinSlot1:
        number: SD1
    coinSlot2:
        number: SD2
    coinSlot3:
        number: SD3
    coinSlot4:
        number: SD4
    exit:
        number: SD5
    down:
        number: SD6
    up:
        number: SD7
    enter:
        number: SD8

    #Regular Switches
    ballLaunch:
        number: S11
    leftHandle:
        number: S12
    startButton:
        number: S13
    plumbBobTilt:
        number: S14
    leftOutlane:
        number: S15
    leftInlane:
        number: S16
    rightInlane:
        number: S17
    rightOutlane:
        number: S18
    slamTilt:
        number: S21
    coinDoor:
        number: S22
    buyIn:
        number: S23
    alwaysClosed:
        number: S24
    clawPos1:
        number: S25
        type: NC
    clawPos2:
        number: S26
        type: NC
    shooterLane:
        number: S27
    unused_S28:
        number: S28
    trough1:
        number: S31
        type: NC
    trough2:
        number: S32
        type: NC
    trough3:
        number: S33
        type: NC
    trough4:
        number: S34
        type: NC
    trough5:
        number: S35
        type: NC
    troughJam:
        number: S36
        type: NC
    unused_S37:
        number: S37
    standUp5:
        number: S38
    leftSlingshot:
        number: S41
    rightSlingshot:
        number: S42
    leftJet:
        number: S43
    topSlingshot:
        number: S44
    rightJet:
        number: S45
    rightRampEnter:
        number: S46
    rightRampExit:
        number: S47
    rightLoop:
        number: S48
    leftRampEnter:
        number: S51
    leftRampExit:
        number: S52
    centerRamp:
        number: S53
    upperRebound:
        number: S54
    leftLoop:
        number: S55
    standUp2:
        number: S56
    standUp3:
        number: S57
    standUp4:
        number: S58
    sideRampEnter:
        number: S61
    sideRampExit:
        number: S62
    leftRollover:
        number: S63
    centerRollover:
        number: S64
    rightRollover:
        number: S65
    eject:
        number: S66
    elevatorIndex:
        number: S67
        type: 'NC'
    unused_S68:
        number: S68
    carChase1:
        number: S71
        type: 'NC'
    carChase2:
        number: S72
        type: 'NC'
    topPopper:
        number: S73
        type: 'NC'
    elevatorHold:
        number: S74
        type: 'NC'
    unused_S75:
        number: S75
    bottomPopper:
        number: S76
        type: 'NC'
    eyeballStandup:
        number: S77
    standUp1:
        number: S78
    clawCaptureSimon:
        number: S81
    clawSuperJets:
        number: S82
    clawPrisonBreak:
        number: S83
    clawFreeze:
        number: S84
    clawAcmag:
        number: S85
    upperLeftFlipperGate:
        number: S86
    carChaseStandup:
        number: S87
    lowerRebound:
        number: S88

PRCoils:
    flipperLwRMain:
        number: FLRM
        pulseTime: 34
    flipperLwRHold:
        number: FLRH
    flipperLwLMain:
        number: FLLM
        pulseTime: 34
    flipperLwLHold:
        number: C32
    flipperUpLMain:
        number: FULM
        pulseTime: 34
    flipperUpLHold:
        number: FULH

    trough:
        number: C01
        # pulseTime 30 was too short for Cardona's "Demolition Time" SW
        pulseTime: 75
    bottomPopper:
        number: C02
    ballLaunch:
        number: C03
        # pulseTime 30 was too short for Cardona's "Demolition Time" SW
        pulseTime: 100
    topPopper:
        number: C04
        pulseTime: 30
    diverterMain:
        number: C05
    unused_C06:
        number: C06
    knocker:
        number: C07
    unused_C08:
        number: C08
    leftSlingshot:
        number: C09
    rightSlingshot:
        number: C10
    leftJet:
        number: C11
    topSlingshot:
        number: C12
    rightJet:
        number: C13
    eject:
        # rewire C14 from 50V to 20V (from neighboring flasher) to get
        # smooth inlane feeds
        number: C14
        pulseTime: 150
    divertorHold:
        number: C15
    unused_C16:
        number: C16
    elevatorMotor:
        number: C18
    clawLeft:
        number: C19
    clawRight:
        number: C20
    clawMagnet:
        number: C33
        patterOnTime: 6
        patterOffTime: 4
    unused_C34:
        number: C34

    # FLASHERS
    clawFlasher:
        number: C17
    jetsFlasher:
        number: C21
    sideRampFlasher:
        number: C22
    leftRampUpperFlasher:
        number: C23
    leftRampLowerFlasher:
        number: C24
    carChaseCenterFlasher:
        number: C25
    carChaseLowerFlasher:
        number: C26
    rightRampLowerFlasher:
        number: C27
    ejectFlasher:
        number: C28
    # flashers on auxiliary 8 driver board
    carChaseUpperFlasher:
        number: C37
    lowerReboundFlasher:
        number: C38
    eyeBallFlasher:
        number: C39
    centerRampFlasher:
        number: C40
    elevator2Flasher:
        number: C41
    elevator1Flasher:
        number: C42
    diverterFlasher:
        number: C43
    rightRampUpFlasher:
        number: C44

PRLamps:
    ballSave:
        number: L11
    fortressMultiball:
        number: L12
    museumMultiball:
        number: L13
    cryoPrisonMultiball:
        number: L14
    wastelandMultiball:
        number: L15
    shootAgain:
        number: L16
    accessClaw:
        number: L17
    leftRampExplode:
        number: L18
    rightRampJackpot:
        number: L21
    rightLoopExplode:
        number: L22
    lightQuickFreeze:
        number: L23
    freeze4:
        number: L24
    clawReady:
        number: L25
    freeze3:
        number: L26
    freeze2:
        number: L27
    freeze1:
        number: L28
    rightLoopJackpot:
        number: L31
    standup5:
        number: L32
    rightRampArrow:
        number: L33
    leftRampJackpot:
        number: L34
    leftLoopJackpot:
        number: L35
    carCrashTop:
        number: L36
    standup1:
        number: L37
    carCrashCenter:
        number: L38
    rightRampExplode:
        number: L41
    rightRampCarChase:
        number: L42
    quickFreeze:
        number: L43
    leftRampCarChase:
        number: L44
    extraBall:
        number: L45
    startMultiball:
        number: L46
    carCrashBottom:
        number: L47
    leftLoopExplode:
        number: L48
    undergroundArrow:
        number: L51
    undergroundJackpot:
        number: L52
    standup2:
        number: L53
    leftRampArrow:
        number: L54
    sideRampJackpot:
        number: L55
    sideRampArrow:
        number: L56
    leftLoopArrow:
        number: L57
    centerRampJackpot:
        number: L58
    clawCaptureSimon:
        number: L61
    clawSuperJets:
        number: L62
    clawPrisonBreak:
        number: L63
    clawFreeze:
        number: L64
    clawAcmag:
        number: L65
    rolloverM:
        number: L66
    rolloverT:
        number: L67
    rolloverL:
        number: L68
    superJackpot:
        number: L71
    computer:
        number: L72
    demolitionTime:
        number: L73
    notUsedL74:
        number: L74
    notUsedL75:
        number: L75
    standup4:
        number: L76
    standup3:
        number: L77
    retinaScan:
        number: L78
    centerRampMiddle:
        number: L81
    centerRampOuter:
        number: L82
    centerRampInner:
        number: L83
    centerRampArrow:
        number: L84
    rightLoopArrow:
        number: L85
    buyInButton:
        number: L86
    ballLaunch:
        number: L87
    startButton:
        number: L88
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05

PRBallSave:
    pulseCoils: [leftSlingshot, rightSlingshot, leftJet, rightJet, bottomJet, eject, topPopper, bottomPopper]
    resetSwitches:
        leftSlingshot: open
        rightSlingshot: open
        leftJet: open
        rightJet: open
        bottomJet: open
        leftOutlane: open
        leftInlane: open
        rightInlane: open
        rightOutlane: open
    stopSwitches:
        shooterLane: closed
        flipperLwL: closed
        flipperLwR: closed

PRPinmame:
    # This section is specific to running the P-ROC via Pinmame.

    # keyboard:
    #   on or off - determines whether keyboard will be enabled or not
    #   useful in a Sys11 in early debugging
    #   Note that this caused problems reading the ball trough on Demolition Man (WPC)

    # s11CreditDisplay and s11BallDisplay :
    #   If using a Sys11 game prior which has a separate Ball/Credit display, you can put them on the
    #   DMD.  If the value for a display is set to zero (or removed from YAML) it won't display.
    #   Otherwise it's the vertical position of the display from the top.  Try 1 and 15 for a start.

    # autoPatterDetection:
    #   on or off - by default, Pinmame will try to automatically detect patter requirements.
    #   there is a thread on the forum about this.  For Sys11 this should certainly be disabled,
    #   as it does nasty things.  Likely enable for other platforms but could be useful to disable.

    # doubleAlpha:
    #   0 or 1 - set to 1 if your machine has 2 lines of 16 character alphanumeric displays.
    #   This will adapt the code to properly handle the various display types in Sys11 machines (and a couple of WPC)

    # fullTroughDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when switches "trough1" through "troughX"
    #            are all active.

    # lightsOutDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when all lamps and GI are off (tilt detection).

    keyboard: off
    autoPatterDetection: off
    s11CreditDisplay: 0
    s11BallDisplay: 0
    doubleAlpha: 0
    fullTroughDisablesFlippers: 0
    lightsOutDisablesFlippers: 0
