# P-ROC Game Description file for FunHouse

PRGame:
    machineType: wpcAlphanumeric
    numBalls: 3

PRFlippers:
    # FunHouse is pre-Fliptronic, and flippers are controlled via hardware
    # instead of software.  Therefore, there isn't a need to list flippers
    # in this section of the YAML.

PRBumpers:
    - slingL
    - slingR
    - lowerJetBumper
    - upperRightJetBumper
    - upperLeftJetBumper

PRSwitches:
    # **** Format ****
    # name:
    #   number: <number>
    #   type: <type>
    #
    #   <number> can be: SFx (Flipper switch, labeled Fx in WPC manual
    #                    SDx (Dedicated switch, labeled SDx in WPC manual
    #                    Sx  (Matrix switch, labeled x in WPC manual
    #   <type> can be: 'NO' (normally open.  This is the default; so no need to use this)
    #    'NC' (normally closed.  Common for optos)

    #dedicated

    coinL:
        number: SD1
        label: 'CoinLeft'
    coinC:
        number: SD2
        label: 'CoinCenter'
    coinR:
        number: SD3
        label: 'CoinRight'
    coin4:
        number: SD4
        label: 'CoinDoor4'
    exit:
        number: SD5
        label: 'Diag Escape'
    down:
        number: SD6
        label: 'Diag Down'
    up:
        number: SD7
        label: 'Diag Up'
    enter:
        number: SD8
        label: 'Diag Enter'

    #matrix
    #col1
    flipperLwR:
        number: S11
        label: 'Left Flipper'
    flipperLwL:
        number: S12
        label: 'Right Flipper'
    startButton:
        number: S13
        label: 'Start Button'
    tilt:
        number: S14
        label: 'Plumb Bob Tilt'
    stepsLightFrenzy:
        number: S15
        label: 'Steps Light Frenzy'
    upperRampSwitch:
        number: S16
        label: 'Upper Ramp Switch'
    stepS:
        number: S17
        label: 'Step S'
    upperLeftJetBumper:
        number: S18
        label: 'Upper Left Jet Bumper'
    #col2
    slamTilt:
        number: S21
        label: 'Slam Tilt'
    frontDoor:
        number: S22
        tags: frontDoor
        label: 'Front Door'
    testPosition:
        number: S24
        tags: testPosition
        label: 'Test Position'
    lockMechRight:
        number: S25
        tags: lockMechRight
        label: 'Lock Mech Right'
    stepsLightExtraBall:
        number: S26
        tags: StepsLightEB, ExtraBall
    lockMechCenter:
        number: S27
        tags: lockMechCenter
        label: 'Lock Mech Center'
    lockMechLeft:
        number: S28
        tags: lockMechLeft
        label: 'Lock Mech Left'
    #col3
    stepP:
        number: S31
        tags: stepP
        label: 'Step P'
    topSuperdogStandupTarget:
        number: S32
        tags: superdog
        label: 'Top Superdog Target'
    upperLeftGangwayRollunder:
        number: S33
        tags: leftGangway
        label: 'Upper Left Gangway Rollunder'
    bottomSuperdogStandupTarget:
        number: S34
        tags: superdog
        label: 'Bottom Superdog Target'
    stepsTrackLower:
        number: S35
        tags: stepsTrackLower
        label: 'Steps Track Lower'
    steps500000:
        number: S36
        label: 'Steps 500,000'
    centerSuperdogStandupTarget:
        number: S37
        tags: superdog
        label: 'Center Superdog Target'
    stepsTrackUpper:
        number: S38
        tags: steps
        label: 'Steps Track Upper'
    #col4
    slingL:
        number: S41
        tags: slingshot, ballAlive
        label: 'Left Slingshot'
    leftFlipperReturnLane:
        number: S42
        tags: return, ballAlive
        label: 'Top Single Drop Target'
    leftOutlane:
        number: S43
        tags: outlane
        label: 'Left Outlane'
    windTunnelHole:
        number: S44
        tags: drop, ballAlive
        label: 'Wind Tunnel Hole'
    trapDoor:
        number: S45
        tags: drop, trapdoor
        label: 'Trap Door'
    rudysHideoutKickbig:
        number: S46
        tags: hideout
        label: 'Rudys Hideout Kickbig'
    shooterL:
        number: S47
        tags: leftBallShooter
        label: 'Left Ball Shooter'
    rampExitTrack:
        number: S48
        tags: rampexit, ballAlive
        label: 'Ramp Exit Track'
#col5
    dummyJaw:
        number: S51
        type: 'NC'
        label: 'Dummy Jaw'
    rightOutlane:
        number: S52
        tags: ballLive
    slingR:
        number: S53
        tags: ballLive
    stepT:
        number: S54
        tags: ballLive
    stepsSuperdog:
        number: S55
        type: 'NC'
        tags: ballLive
    rampEntrance:
        number: S56
        tags: ballLive
    jetBumperLane:
        number: S57
        tags: ballLive
    tunnelKickout:
        number: S58
        tags: ballLive

    #col6
    rInsideFlprRtrn:
        number: S61
    shooterR:
        number: S62
        tags: ballLive
    trough1:
        number: S63
    stepE:
        number: S64
        tags: ballLive
    dummyEjectHole:
        number: S65
    upperRightGangwayLane:
        number: S66
        tags: ballLive
    lowerRightDropHole:
        number: S67
        tags: ballLive
    lowerJetBumper:
        number: S68
        tags: ballLive

    #col 7

    rOutsideFlprRtrn:
        number: S71
    trough3:
        number: S72
    outhole:
        number: S73
    trough2:
        number: S74
    upperRightLoop:
        number: S75
        tags: ballLive
    trapDoorClosed:
        number: S76
    upperRightJetBumper:
        number: S77

PRCoils:

    # Flipper coils aren't under software control, and are therefore not
    # listed in this section.

    outhole:
        number: C01
        label: 'Outhole'
    rampDiverter:
        number: C02
        label: 'Ramp Diverter'
    kickbig:
        number: C03
        label: 'Kickbig'
    tunnelKickbig:
        number: C04
        pulseTime: 50
        label: 'Tunnel Kickbig'
    trapDoorOpen:
        number: C05
        label: 'Trap Door Open'
    trapClosed:
        number: C06
        label: 'Trap Closed'
    knocker:
        number: C07
        label: 'Knocker'
    multiballRelease:
        number: C08
        pulseTime: 50
        label: 'Multiball Release'
    upperLeftJetBumper:
        number: C09
        label: 'Upper Left Jet Bumper'
    upperRightJetBumper:
        number: C10
        label: 'Upper Right Jet Bumper'
    lowerJetBumper:
        number: C11
        label: 'Lower Jet Bumper'
    slingL:
        number: C12
        label: 'Left Slingshot'
    slingR:
        number: C13
        label: 'Right Slingshot'
    stepsGate:
        number: C14
        label: 'Steps Gate'
    trough:
        number: C15
        label: 'Trough'
    dummyEjectHole:
        number: C16
        label: 'Dummy Eject Hole'
    blueFlashers:
        number: C17
        label: 'Blue Flashers'
    dummyFlasher:
        number: C18
        label: 'Dummy Flasher'
    clockFlashers:
        number: C19
        label: 'Clock Flashers'
    superdogs:
        number: C20
        label: 'Superdogs'
    mouthMotor:
        number: C21
        label: 'Mouth Motor'
    upDownDriver:
        number: C22
        label: 'Up/Down Driver'
    redFlashers:
        number: C23
        label: 'Red Flashers'
    clearFlashers:
        number: C24
        label: 'Clear Flashers'
    eyesRight:
        number: C25
        label: 'Eyes Right'
    eyelidsOpen:
        number: C26
        label: 'Eyelids Open'
    eyelidsClosed:
        number: C27
        label: 'Eyelids Closed'
    eyesLeft:
        number: C28
        label: 'Eyes Left'

PRLamps:
    #col1
    gangway75000:
        number: L11
        label: 'Gangway 75,000'
    gangway100000:
        number: L12
        label: 'Gangway 100,000'
    gangway150000:
        number: L13
        label: 'Gangway 150,000'
    gangway200000:
        number: L14
        label: 'Gangway 200,000'
    gangway250000:
        number: L15
        label: 'Gangway 250,000'
    gangwayLightsEB:
        number: L16
        label: 'Gangway Lights Extra Ball'
    shootAgain:
        number: L17
        label: 'Shoot Again'
    stepsOpen:
        number: L18
        label: 'Steps Open'
    clock45Minutes:
        number: L21
        label: 'Clock 45 Minutes'
    clock8oClock:
        number: L22
        label: 'Clock 8 oClock'
    clock6oClock:
        number: L23
        label: 'Clock 6 oClock'
    clock25Minutes:
        number: L24
        label: 'Clock 25 Minutes'
    clock15Minutes:
        number: L25
        label: 'Clock 15 Minutes'
    clock10Minutes:
        number: L26
        label: 'Clock 10 Minutes'
    clock12Minutes:
        number: L27
        label: 'Clock 12 Minutes'
    clock0Minutes:
        number: L28
        label: 'Clock 0 Minutes'
    clock40Minutes:
        number: L31
        label: 'Clock 40 Minutes'
    clock35Minutes:
        number: L32
        label: 'Clock 35 minutes'
    clock30Minutes:
        number: L33
        label: 'Clock 30 Minutes'
    clock20Minutes:
        number: L34
        label: 'Clock 20 Minutes'
    clock3oClock:
        number: L35
        label: 'Clock 3 oClock'
    clock1oClock:
        number: L36
        label: 'Clock 1 oClock'
    clock11oClock:
        number: L37
        label: 'Clock 11 oClock'
    clock50Minutes:
        number: L38
        label: 'Clock 50 Minutes'
    clock9oClock:
        number: L41
        label: 'Clock 9 oClock'
    clock7oClock:
        number: L42
        label: 'Clock 7 oClock'
    clock5oClock:
        number: L43
        label: 'Clock 5 oClock'
    clock4oClock:
        number: L44
        label: 'Clock 4 oClock'
    clock2oClock:
        number: L45
        label: 'Clock 2 oClock'
    clock5Minutes:
        number: L46
        label: 'Clock 5 Minutes'
    clock55Minutes:
        number: L47
        label: 'Clock 55 Minutes'
    clock10oClock:
        number: L48
        label: 'Clock 10 oClock'
    lowerLeftJetBumper:
        number: L51
        label: 'Lower Left Jet Bumper'
    upperLeftJetBumper:
        number: L52
        label: 'Upper Left Jet Bumper'
    superdogLamp:
        number: L53
        label: 'Superdog Lamp'
    stepsLightsFrenzy:
        number: L54
        label: 'Steps Light Frenzy'
    stepsLightsEB:
        number: L55
        label: 'Steps Light Extra Ball'
    steps500000:
        number: L56
        label: 'Steps 500,000'
    rampOverheadLamp:
        number: L57
        label: 'Ramp Overhead Lamp'
    rightGangwayOverheadLamp:
        number: L58
        label: 'Right Gangway Overhead Lamp'
    leftAndInsideRightFlipperLanes:
        number: L61
        label: 'Left and Inside Right Flipper Lanes'
    stepS:
        number: L62
        label: 'Step S'
    trapDoorBonus:
        number: L63
        label: 'Trap Door Bonus'
    rampScores250000:
        number: L64
        label: 'Ramp Scores 250,000'
    stepT:
        number: L65
        label: 'Step T'
    upperLeftGangwayLane:
        number: L66
        label: 'Upper Left Gangway Lane'
    extraBallLamp:
        number: L67
        label: 'Extra Ball Lamp'
    lock:
        number: L68
        label: 'Lock'
    magicMirrorLightsEB:
        number: L71
        label: 'Magic Mirror Lights Extra Ball'
    upperRightJetBumper:
        number: L72
        label: 'Upper Right Jet Bumper'
    stepP:
        number: L73
        label: 'Step P'
    magicMirrorLightsMillion:
        number: L74
        label: 'Magic Mirror Lights Million'
    magicMirrorLightsJetBumpers:
        number: L75
        label: 'Magic Mirror Lights Jet Bumpers'
    magicMirrorLightsSuperdog:
        number: L76
        label: 'Magic Mirror Lights Superdog'
    magicMirrorOpensGate:
        number: L77
        label: 'Magic Mirror Opens Gate'
    magicMirrorLightsQuickMB:
        number: L78
        label: 'Magic Mirror Lights Quick Multiball'
    millionPlus:
        number: L81
        label: 'Million Plus'
    specialOutlanes:
        number: L82
        label: 'Special Outlanes'
    trapDoorFrenzy:
        number: L83
        label: 'Trap Door Frenzy'
    rampStepsLamp:
        number: L84
        label: 'Ramp Steps Lamp'
    magicMirrorArrow:
        number: L85
        label: 'Magic Mirror Arrow'
    stepE:
        number: L86
        label: 'Step E'
    million:
        number: L87
        label: 'Million'
    startButton:
        number: L88
        label: 'Start'
    gi01:
        number: G01
    gi02:
        number: G02
    gi03:
        number: G03
    gi04:
        number: G04
    gi05:
        number: G05
    flipperEnable:
        number: G08

PRBallSave:
    pulseCoils: [slingL, slingR, upperLeftJetBumper, upperRightJetBumper, lowerJetBumper, dummyEjectHole, kickbig, tunnelKickbig, knocker, multiballRelease]
    resetSwitches:
        slingL: open
        slingR: open
        lowerJetBumper: open
        upperLeftJetBumper: open
        upperRightJetBumper: open
        #leftOutlane: open
        #leftAndInsideRightFlipperLanes: open
        #rightOutlane: open
        #rInsideFlprRtrn: open
        #rOutsideFlprRtrn: open
        #rightCellar: open
        #rightRampMadeTop: open
        #spinner: open
    stopSwitches:
        #leftCellar: closed
        outhole: closed
        shooterR: closed
        #flipperLwL: closed
        #flipperLwR: closed

PRDriverGlobals:
    lamp_matrix_strobe_time: 200
    use_watchdog: True
    watchdog_time: 1000

PRPinmame:
    # This section is specific to running the P-ROC via Pinmame.

    # keyboard:
    #   on or off - determines whether keyboard will be enabled or not
    #   useful in a Sys11 in early debugging
    #   Note that this caused problems reading the ball trough on Demolition Man (WPC)

    # s11CreditDisplay and s11BallDisplay :
    #   If using a Sys11 game prior which has a separate Ball/Credit display, you can put them on the
    #   DMD.  If the value for a display is set to zero (or removed from YAML) it won't display.
    #   Otherwise it's the vertical position of the display from the top.  Try 1 and 15 for a start.

    # autoPatterDetection:
    #   on or off - by default, Pinmame will try to automatically detect patter requirements.
    #   there is a thread on the forum about this.  For Sys11 this should certainly be disabled,
    #   as it does nasty things.  Likely enable for other platforms but could be useful to disable.

    # doubleAlpha:
    #   0 or 1 - set to 1 if your machine has 2 lines of 16 character alphanumeric displays.
    #   This will adapt the code to properly handle the various display types in Sys11 machines (and a couple of WPC)

    # fullTroughDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when switches "trough1" through "troughX"
    #            are all active.

    # lightsOutDisablesFlippers:
    #   0 or 1 - Set to 1 to disable flippers when all lamps and GI are off (tilt detection).

    keyboard: off
    autoPatterDetection: off
    s11CreditDisplay: 0
    s11BallDisplay: 0
    doubleAlpha: 1
    fullTroughDisablesFlippers: 0
    lightsOutDisablesFlippers: 0
